In [13]:
import pandas as pd

# PATH = 'data/results/full_gold_run/en_gold_all.csv'
PATH = 'data/results/6_lower_sense_proper_quoting/lower_sense.csv'

df = pd.read_csv(PATH)

In [14]:
# Best scoring sentences
df.sort_values('f1_lenient', ascending=False).head(20)

,pmb_id,raw_sent,precision,recall,f1,precision_lenient,recall_lenient,f1_lenient
4674,en/p57/d2592,I played the accordion.,0.941176,0.941176,0.941176,1.0,1.0,1.0
1653,en/p51/d2707,I failed chemistry.,0.941176,0.941176,0.941176,1.0,1.0,1.0
8508,en/p01/d2455,I was coughing.,1.000000,1.000000,1.000000,1.0,1.0,1.0
4828,en/p07/d2560,The girls giggled.,1.000000,1.000000,1.000000,1.0,1.0,1.0
7268,en/p00/d0865,I threw up.,1.000000,1.000000,1.000000,1.0,1.0,1.0
7226,en/p00/d2884,I was crying.,0.928571,0.928571,0.928571,1.0,1.0,1.0
5929,en/p09/d2518,I ordered pizza.,0.941176,0.941176,0.941176,1.0,1.0,1.0
7197,en/p00/d3417,We rented a canoe.,0.941176,0.941176,0.941176,1.0,1.0,1.0
7185,en/p00/d0908,I won the gold medal.,1.000000,1.000000,1.000000,1.0,1.0,1.0
3546,en/p41/d2372,I booked the field.,0.882353,0.882353,0.882353,1.0,1.0,1.0
5989,en/p09/d1939,I have borrowed a table.,0.941176,0.941176,0.941176,1.0,1.0,1.0
8713,en/p01/d2119,We exaggerated.,1.000000,1.000000,1.000000,1.0,1.0,1.0
8751,en/p10/d2140,I skipped breakfast.,0.941176,0.941176,0.941176,1.0,1.0,1.0
7076,en/p00/d1807,I phoned.,1.000000,1.000000,1.000000,1.0,1.0,1.0
3015,en/p27/d3174,I was playing tennis.,1.000000,1.000000,1.000000,1.0,1.0,1.0
7050,en/p00/d3129,I brought wine.,1.000000,1.000000,1.000000,1.0,1.0,1.0
7049,en/p00/d1998,I ate.,0.928571,0.928571,0.928571,1.0,1.0,1.0
2989,en/p30/d2755,I caught a fish!,0.941176,0.941176,0.941176,1.0,1.0,1.0
10409,en/p76/d2001,A dog chased a cat.,1.000000,1.000000,1.000000,1.0,1.0,1.0
3572,en/p41/d1936,The car was stolen.,1.000000,1.000000,1.000000,1.0,1.0,1.0

In [15]:
df[df.f1_lenient > .8]

,pmb_id,raw_sent,precision,recall,f1,precision_lenient,recall_lenient,f1_lenient
0,en/p12/d2513,She planted some pansies in the flower bed.,0.800000,0.888889,0.842105,0.866667,0.928571,0.896552
5,en/p12/d3517,I owed him a thousand dollars.,0.772727,0.680000,0.723404,0.875000,0.756757,0.811594
11,en/p12/d3247,Tom videotaped it.,0.882353,0.882353,0.882353,0.920000,0.920000,0.920000
22,en/p12/d2518,Tom has gone to Boston.,0.789474,0.789474,0.789474,0.851852,0.851852,0.851852
23,en/p12/d0877,I was invited by an old friend.,0.800000,0.695652,0.744186,0.933333,0.800000,0.861538
...,...,...,...,...,...,...,...,...
10659,en/p20/d1958,Who escaped?,0.785714,0.785714,0.785714,0.850000,0.850000,0.850000
10660,en/p20/d2498,Tom dug a hole in the backyard.,0.750000,0.750000,0.750000,0.900000,0.900000,0.900000
10661,en/p20/d1616,Tom is playing poker with his friends.,0.761905,0.666667,0.711111,0.870968,0.750000,0.805970
10663,en/p20/d2206,Are you sleeping with her?,0.705882,0.705882,0.705882,0.800000,0.800000,0.800000
10666,en/p20/d1847,I love Hitomi.,0.736842,0.736842,0.736842,0.851852,0.851852,0.851852

In [16]:
# Worst scoring sentences
# df.sort_values('f1_lenient', ascending=True).head(50)
df.sort_values('f1', ascending=True).head(40)

,pmb_id,raw_sent,precision,recall,f1,precision_lenient,recall_lenient,f1_lenient
8110,en/p80/d0813,All of us talk in English.,0.187500,0.157895,0.171429,0.500000,0.444444,0.470588
7234,en/p00/d1936,My watch may be one or two minutes fast.,0.260870,0.166667,0.203390,0.485714,0.340000,0.400000
9241,en/p33/d2982,The square root of one hundred forty-four is t...,0.160000,0.363636,0.222222,0.189189,0.466667,0.269231
4724,en/p52/d2324,Fifteen is not a prime number.,0.214286,0.272727,0.240000,0.300000,0.400000,0.342857
9565,en/p88/d2319,He who risks not gains not.,0.217391,0.277778,0.243902,0.314286,0.458333,0.372881
9007,en/p22/d3215,You can't tickle yourself.,0.235294,0.266667,0.250000,0.320000,0.421053,0.363636
6747,en/p59/d2962,"It's not your fault, it's Alison's.",0.320000,0.205128,0.250000,0.567568,0.368421,0.446809
8412,en/p74/d2359,A top-class shearer can shear up to 150 sheep ...,0.320000,0.210526,0.253968,0.540541,0.357143,0.430108
6716,en/p35/d2432,"In case of emergency, call 119.",0.312500,0.217391,0.256410,0.541667,0.393939,0.456140
8883,en/p10/d0830,Nobody can surpass him.,0.235294,0.285714,0.258065,0.440000,0.550000,0.488889
3642,en/p77/d2877,None of us can speak French.,0.277778,0.263158,0.270270,0.500000,0.518519,0.509091
10489,en/p56/d2381,Two times seven is fourteen.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
4578,en/p31/d1839,Four times five is 20.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
2465,en/p13/d2643,Four plus eighteen is twenty-two.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
379,en/p61/d2802,Three times five is fifteen.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
9459,en/p23/d3358,Three times three is nine.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
4261,en/p26/d2348,She may spill the beans.,0.235294,0.333333,0.275862,0.440000,0.611111,0.511628
10232,en/p21/d0807,Four times five is twenty.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
2317,en/p32/d2926,Two is the fourth root of sixteen.,0.250000,0.307692,0.275862,0.363636,0.470588,0.410256
942,en/p48/d2030,Three times four is twelve.,0.250000,0.307692,0.275862,0.318182,0.411765,0.358974
8426,en/p74/d3409,Her manners are not those of a lady.,0.277778,0.277778,0.277778,0.535714,0.535714,0.535714
4057,en/p70/d2331,You should be ashamed of your stupidity.,0.250000,0.312500,0.277778,0.400000,0.545455,0.461538
8221,en/p58/d3087,Neither Tom nor Mary can speak French.,0.350000,0.233333,0.280000,0.600000,0.428571,0.500000
8852,en/p10/d1901,Maybe he is Italian or Spanish.,0.400000,0.222222,0.285714,0.500000,0.300000,0.375000
7061,en/p00/d2440,Eight plus two is ten.,0.285714,0.307692,0.296296,0.350000,0.411765,0.378378
2232,en/p85/d2634,Four plus three is seven.,0.285714,0.307692,0.296296,0.350000,0.411765,0.378378
746,en/p16/d1524,Mr. Smith is liked by all the students.,0.470588,0.216216,0.296296,0.680000,0.309091,0.425000
4363,en/p26/d0896,Five plus three is eight.,0.285714,0.307692,0.296296,0.350000,0.411765,0.378378
6325,en/p04/d2907,The submarine can dive up to a 1000 feet.,0.352941,0.260870,0.300000,0.600000,0.428571,0.500000
5856,en/p02/d0795,"John is not my brother, but my cousin.",0.500000,0.214286,0.300000,0.653846,0.283333,0.395349
2209,en/p85/d2115,The appendix is about 10 cm long.,0.333333,0.280000,0.304348,0.575758,0.513514,0.542857
5696,en/p99/d3447,A whale is a mammal.,0.333333,0.285714,0.307692,0.611111,0.550000,0.578947
207,en/p96/d0802,A dolphin is a mammal.,0.333333,0.285714,0.307692,0.611111,0.550000,0.578947
8782,en/p10/d3307,It's eleven and he's not coming.,0.318182,0.304348,0.311111,0.468750,0.483871,0.476190
3120,en/p17/d2440,All of them are not present.,0.454545,0.238095,0.312500,0.764706,0.448276,0.565217
8767,en/p10/d2993,All journeys begin with a first step.,0.277778,0.357143,0.312500,0.392857,0.550000,0.458333
4392,en/p47/d2248,He can also speak Russian.,0.250000,0.416667,0.312500,0.400000,0.666667,0.500000
8816,en/p10/d2714,They have to go to school.,0.250000,0.416667,0.312500,0.400000,0.666667,0.500000
4374,en/p26/d2570,One cannot trust surveys.,0.357143,0.277778,0.312500,0.550000,0.458333,0.500000
5737,en/p02/d2389,All of us like her.,0.428571,0.250000,0.315789,0.681818,0.441176,0.535714

In [17]:
# Get long sentences that score high
df.sort_values("raw_sent", key=lambda x: x.str.len(), ascending=False) \
    .head(200) \
    .sort_values('f1_lenient', ascending=False) \
    [['pmb_id', 'raw_sent', 'f1', 'f1_lenient']]

,pmb_id,raw_sent,f1,f1_lenient
9401,en/p69/d2947,The exchange rate of the dollar versus the eur...,0.777778,0.892857
4332,en/p26/d0712,Leloir won the Premio de la Sociedad Científic...,0.842105,0.888889
3462,en/p63/d1248,The body was discovered in a warehouse in the ...,0.761905,0.878788
1974,en/p11/d2092,The Sioux had signed a treaty with the governm...,0.809524,0.870968
5751,en/p02/d1539,The weather is clearing up. I needn't have bro...,0.774194,0.866667
...,...,...,...,...
6527,en/p94/d1295,"On October 2, 1942, he was at the Swiss border...",0.464286,0.525000
2168,en/p39/d1422,"Her name was Linda, and she was a year younger...",0.414634,0.524590
657,en/p38/d1998,George Washington was born on the twenty secon...,0.408163,0.507463
4399,en/p47/d0755,The Salt Lake City 2002 Winter Olympics will t...,0.390625,0.477778
9481,en/p23/d1469,"Helium, neon, argon, krypton, xenon and radon ...",0.407767,0.448485